---
title: "HOBO Data"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(seacarb)

setwd("C:/Users/Kelsey.Donahue/Documents/HOBO")
file.names <- dir(getwd(),pattern=".csv")
file.names


```

## Including Plots
```{r}

readTidbit <- function(file.names){
  df <- read.csv(file.names, skip = 1)
  df <- subset(df, select = c(2, 3)) 
  names(df) <- c("Date", "Value")
  df$DataType <- "temperature"
  return(df)
}

readDOtemp <- function(file.names){
  df <- read.csv(file.names, skip = 1)
  df <- subset(df, select = c(2, 4))
  names(df) <- c("Date", "Value")
  df$DataType <- "temperature"
  return(df)
}

readDOoxygen <- function(file.names){
  df <- read.csv(file.names, skip = 1)
  df <- subset(df, select = c(2, 3))
  names(df) <- c("Date", "Value")
  df$DataType <- "DO"
  return(df)
}



readCond <- function(file.names){
  df <- read.csv(file.names, skip = 1)
  df <- subset(df, select = c(2, 6))
  names(df) <- c("Date", "Value")
  df$DataType <- "SpecificConductivity"
}

readLight<- function(file.names){
  df <- read.csv(file.names, skip = 1)
  df <- subset(df, select = c(2, 4))
  names(df) <- c("Date", "Value")
  df$DataType <- "Light"
}

readAirTemp <- function(file.names){
  df <- read.csv(file.names, skip = 1)
  df <- subset(df, select = c(2,3))
  names(df) <- c("Date", "Value")
  df$DataType <- "Air Temp"
}
  
d <- data.frame("Date" = character(0), "Value" = numeric (0), "DataType" = character(0), "SerialNumber" = character(0)) 

if(grepl("20449374", file.names[i])){
     dt <- readCond(file.names[i])
     dt$SerialNumber <- 20449374
     d <- rbind(d,dt)

     
     #For all columns wanted and loggers
for(i in 1:length(file.names)){
if(grepl(00264, file.names[i])){
     dl <- readLight(file.names[i])
     dl$SerialNumber <- 00264
     d <- rbind(d, dl)
  }
}
View(d)

for(i in 1:length(file.names)){
   if(grepl(20432185, file.names[i])){
     dt <- readTidbit(file.names[i])
     dt$SerialNumber <- 20432185
     d <- rbind(d,dt)
  }
  if(grepl(20432184, file.names[i])){
    dt <- readTidbit(file.names[i])
    dt$SerialNumber <- 20432184
    d <- rbind(d,dt)
  }
}
  if(grepl(20449374, file.names[i])){
     dt <- readCond(file.names[i])
     dt$SerialNumber <- 20449374
     d <- rbind(d,dt)
  }
}
   if(grepl(20454092 || DO, file.names[i])){
     dt <- readDOtemp(file.names[i])
     dt$SerialNumber <- 20454092
     d <- rbind(d,dt)
  }
   if(grepl(20454092 || DO, file.names[i])){
     dt <- readDOoxygen
     dt$SerialNumber <- 20454092
     d <- rbind(d,dt)
   }
   if(grepl(11111, file.names[i])){
     dt <- readLight(file.names[i])
     dt$SerialNumber <- 11111
     d <- rbind(d,dt)
   }
   if(grepl(11111, file.names[i])){
     dt <- readAirTemp(file.names[i])
     dt$SerialNumber <- 11111
     d <- rbind(d,dt)
    }
     if(grepl(00264, file.names[i])){
     dt <- readLight(file.names[i])
     dt$SerialNumber <- UA-002-64
     d <- rbind(d,dt)
     }


   if(grepl(00264, file.names[i])){
     dt <- readAirTemp(file.names[i])
     dt$SerialNumber <- UA-002-64
     d <- rbind(d,dt)
     }
}












#tried to merge all

= function(mypath){
  file.names=list.files(path=mypath, full.names=TRUE) 
  datalist = lapply(file.names, function(x)(read.csv))
  Reduce(function(x,y) (merge(x,y)), datalist)
}

# was making separate data frame 
#setwd("C:/Users/Kelsey.Donahue/Documents/HOBO/TidBit")
file.namesTid <- dir(getwd(),pattern=".csv")
file.namesTid

#d <- data.frame(DateTime = character(0), TidTemp  = numeric(0))

#for(i in 1:length(file.namesTid)) {
  dTemp <- read.csv(file.namesTid[i], skip = 1)
  dTemp <- dTemp[ ,c(2,3)]
  names(dTemp) <- c("DateTime", "TidTemp")
  d <- rbind(d, dTemp)
}
```

You can also embed plots, for example:

```{r}
 
d$Time <- format(d$Time, "%H:%M")

#Picking out these rows to represent 10-16-2018 because I couldn't figure out how to subset out that day
dsubTemp <- d[1:101,]

ggplot(dsubTemp, aes(Time, Temperature)) +
  geom_point() + theme_bw() + theme(axis.text.x = element_text(angle = 80, hjust = 1)) 



```





```{r}
d$Date <- as.Date(d$Date)
plotTemp <- ggplot(d, aes(Time, Temperature)) + theme_bw() +
  geom_point() + ggtitle("HOBO Temperature") + xlab("Time") +
  facet_wrap(~ Date)

plot(plotTemp)
  
```
```{r}
setwd("C:/Users/Kelsey.Donahue/Documents/HOBO")
file.names
d <- read_xlsx("HOBO_Logger_CrabCorner_TempLight.xlsx")
```
