---
title: "Dissolve Oxygen Timeseries, Juvenile Exposure Study, HOBOlogger Data Import"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: cerulean
    highlight: haddock
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC
Title: Salmon Shed Tanks - Dissolved Oxygen
Date: 2018-2019 (R document March 2021)


# Version Check
```{r 0.1 Version Check , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Version Check
#********************************* 
R.version

```



# Libraries
```{r 0.0 Libraries , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
##Libraries
#********************************* 
library(here)
library(stringr)
library(data.table)
library(tidyverse)
library(plyr)
library(nlme)
library(tidyr)
library(dbplyr)
library(dplyr)
library(purrr)
library(wql)
library(lubridate)
library(tibbletime)
library(arsenal)
library(compareDF)
library(metacsv)
#for graphing
library(ggplot2)
library(ggfortify)
library(stringr)
library(nlme)
library(RColorBrewer)
library(patchwork)
#statistical analysis
library(gdata)
library(rsq)
library(doBy)
#Rnotebooks 
library(gridExtra)
library(kableExtra)

```




# 1.) Setting Working Directory
```{r 1.) Setting Working Directory, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE }
#*********************************
## 1.) Setting Working Directory
#*********************************

#set working directory to the correct folder
# setwd("/Users/katherinerovinski/GIT/NWFSC.MUK_DGNjuvenile.tanks")
setwd("/Users/katherinerovinski/GIT/NWFSC.MUK_DGNjuvenile.tanks/HOBO Data/logger_DOprobe")

```



# 2.) Creating the Dataframe
```{r 2.) Creating the Dataframe, echo=FALSE, message=FALSE, warning=FALSE}

#*********************************
## 2.) Creating the initial Dataframes
#*********************************

setwd("/Users/katherinerovinski/GIT/NWFSC.MUK_DGNjuvenile.tanks/HOBO Data/logger_DOprobe")

## Create a list of files 
# All files to be joined have ext. "csv" can use that pattern to join 
files <- list.files(pattern = ".csv")
print(files)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |
## 2.2 Create a temporary place for files 
temp <- lapply(files, fread, sep= ",")
print(temp)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |
## 2.3 Create a new vector for Moats data logs 
# DO logger list
loggerDO <- rbindlist(temp, fill=TRUE)
print(loggerDO)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

names(loggerDO)

# write.csv(loggerDO, file = "CRB_JUV_AmbientConditions_2018_to_2019loggerDO.csv", row.names = FALSE)

loggerDO <- as.numeric(loggerDO$`DO Percent Sat, % (LGR S/N: 20454092)`)

names(loggerDO)
loggerDO <- as.data.frame(loggerDO)


loggerDO <- loggerDO  %>% 
              rename(dateTime = "Date Time, GMT-07:00") %>%
              # rename(DOconcentation_mg.L="DO conc, mg/L (LGR S/N: 20454092, SEN S/N: 20454092)") %>%
              # rename(Temp="Temp, °C (LGR S/N: 20454092, SEN S/N: 20454092)") %>%
              # rename(DOadjConc="DO Adj Conc, mg/L (LGR S/N: 20454092)") %>%
              # rename(DOpercentSat="DO Adj Conc, mg/L (LGR S/N: 20454092)") %>%
              {.}

# {.} this means nothing- nice tester line

# loggerDO[1, "#"] <- "sequence"
# rename.variable(loggerDO, "#, "sequence")
# loggerDO[2, "Date Time, GMT-07:00"] <- "dateTime"
# loggerDO[3, "DO conc, mg/L (LGR S/N: 20454092, SEN S/N: 20454092)"] <- "DOconcentration_mgL"
# loggerDO[4, "Temp, °C (LGR S/N: 20454092, SEN S/N: 20454092)"] <- "temp"
# loggerDO[5, "DO Adj Conc, mg/L (LGR S/N: 20454092)"] <- "DOadjConc"
# loggerDO[6, "DO Percent Sat, % (LGR S/N: 20454092)"] <- "DPpercentSat"





```





# 3.) Creating dateTime objects 
```{r 3.) Creating dateTime objects, echo=FALSE, message=FALSE, warning=FALSE }
#*********************************
## 3.) Creating dateTime objects  
#*********************************



# logDOprobe$ObservationDate <- ""
# logDOprobe$ObservationDate <- as.POSIXct(logDOprobe$dateTime, tz = "UTC", "%m/%d/%y %H:%M")



loggerDO$ObservationDate <- ""

loggerDO$`Date Time, GMT-07:00` <- as.Date(loggerDO$`Date Time, GMT-07:00`)

loggerDO$ObservationDate <- as.POSIXct(loggerDO$Date Time, tz = "UTC", "%m/%d/%y %H:%M")


```


# 4.) DO probe timeseries
```{r DO probe timeseries}

ggplot(loggerDO, aes(loggerDO$`Date Time, GMT-07:00`, (loggerDO$`DO conc, mg/L (LGR S/N: 20454092, SEN S/N: 20454092)`)) +
  geom_point() +
  # ylim(24,33) +
  ggtitle("DO Concentration") +
  geom_blank


```




```{r}
#**************E*N*D*************# 
#*********************************
## END OF SCRIPT | END OF DOCUMENT 
#*********************************
```


## END OF SCRIPT | END OF DOCUMENT



















